travis:
  secure:
    BINSTAR_TOKEN: LQqfjW1iCstGU8zuyWv5bDGPSQC1xqu+M++vBI6WdwiFQc+//OnBqynqa785Tq0kPjPzhWH6jobr97fpPoZ+R11k2NqOl9cuW63WXj9cA1Ai8vQB/CvahaiaVlrDIDItGHO3WmeQIATwzY5Fb0tZCBKmkaLkB9hm7W2QsUiMOQYvk3teaIHf4bAgmvz8gpJSPwvV/ENf603dL7QO4mP17giXELWOFh3MT6t8p6Yp9H1wSg/F55UpWk+HcDKnb1o4r+SZOa1sDtmV3RFGRkk6O5rvmcor8jAIbdA3ROFB3k1tlCs8+rJNKiq6PquqjXHAA+cdhGlffSjoNLJDe7F1h7EMHRAZekymqEpNQ6Ah775bo9UPVLnLtl62ko4cvz4uQo7LC+58rqA8107IkhE+wbDT2F3OR8gGowkopfAFNf4pMOLIRgJgWVHYLK6TvoHaFzahlyieu2KOjUHhoXEziRxL9sZglxi5Clf2HQxNfYHrMikP+uQR8z0fbAi38yVZeE10x2vCeeIF+0lGqiJOzilIZutmXmjLg+HuFLPqut9LAr15NMwhupCasSsvMbQ2yCipKjozUizrHJvwWIdqtmD7UNoedRbQk6k4J6G87HQgFsjwpmTd+PGW9eFyU/4c+XI5iSp7re11uOv3rFLwpI5N+SJieMLUGEsIT/i5IM8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
